version: '3'
services:
 web:
   container_name: "python3"
   build: ./backend
   command: python3 manage.py runserver 0.0.0.0:8000
   working_dir: /code
   ports:
     - 8888:8000
   volumes:
     - ./backend:/code
   depends_on:
     - db
 db:
   container_name: "mysql"
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_DATABASE: "Todo"
     MYSQL_USER: hiroto
     MYSQL_PASSWORD: hiroto
     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
   volumes:
     - ./mysql:/var/lib/mysql
   ports:
     - 3306:3306
 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS='db'
    ports:
      - "3333:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
 react:
    build:
      context: ./frontend
    image: react
    volumes:
      - ./frontend/react-app:/usr/src/app
    command: sh -c "yarn install && yarn start"
    tty: true
    ports:
      - 3000:3000
